# Generated by Django 5.2.11 on 2026-02-21 01:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(help_text='e.g., bottles, pieces, towels', max_length=50)),
                ('allocation_type', models.CharField(choices=[('TRAINING', 'Training Center'), ('NC2', 'NC II Assessment')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockOutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_deducted', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('release_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Reason for stock out or recipient', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='app.item')),
                ('released_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
